experiment_name: "Example1"
seed: 42

model:
  architecture: "tcn"
  params:
    input_size: 40  # Number of input features (e.g., MFCC features)
    output_size: 1  # EDA signal output
    num_blocks: 5
    num_channels: 64
    kernel_size: 3
    dropout: 0.2

optimizer:
  name: "adamw"
  learning_rate: 0.0001
  weight_decay: 0.01

data:
  train_datasets:
    - hku956
  val_datasets:
    - hku956
  test_datasets:
    - hku956
  num_workers: 4
  prefetch_size: 2

batch_size: 32

loss:
  name: "mse"

hardware:
  device: "mps"
  precision: "fp32"  # MPS only supports fp32
  distributed: False # MPS doesn't support distributed training
  num_gpus: 1        # MPS only supports a single GPU

logging:
  wandb_project: "audio2eda"
  wandb_run_name: "Example1_Run"
  log_every_n_steps: 50
  train_metrics:
    - "loss"
  val_metrics:
    - "loss"
    - "mse"

checkpoint:
  save_top_k: 3
  checkpoint_dir: "checkpoints/example1"
  monitor: "val_loss"
  mode: "min"
  save_last: True
  save_every_n_steps: 1000
