experiment_name: "Example2"
seed: 42

model:
  architecture: "wavenet"
  params:
    num_stacks: 3
    num_layers_per_stack: 10
    residual_channels: 64
    skip_channels: 128
    kernel_size: 3
    dilation_base: 2
    dropout_rate: 0.2
    input_channels: 40
    output_channels: 1
    use_bias: true

optimizer:
  name: "adam"
  learning_rate: 0.0005
  weight_decay: 0.001
  scheduler: "cosine"

data:
  train_datasets:
    - pmemo2019
  val_datasets:
    - pmemo2019
  test_datasets:
    - pmemo2019
  num_workers: 8
  prefetch_size: 4

batch_size: 64

loss:
  name: "huber"

hardware:
  device: "cuda"
  precision: "fp16"
  distributed: True
  num_gpus: 2

logging:
  wandb_project: "audio2eda"
  wandb_run_name: "Example2_Run"
  log_every_n_steps: 25
  train_metrics:
    - "loss"
  val_metrics:
    - "loss"
    - "mse"
    - "dtw"

checkpoint:
  save_top_k: 5
  checkpoint_dir: "checkpoints/example2"
  monitor: "val_dtw"
  mode: "min"
  save_last: True
  save_every_n_steps: 500
