experiment_name: "Example2"
seed: 42

model:
  architecture: "wavenet"
  params:
    num_stacks: 3
    num_layers_per_stack: 10
    residual_channels: 64
    skip_channels: 128
    kernel_size: 3
    dilation_base: 2
    dropout_rate: 0.2
    input_channels: 40
    output_channels: 1
    use_bias: true

optimizer:
  name: "adam"
  learning_rate: 0.0005
  weight_decay: 0.001
  beta1: 0.9
  beta2: 0.999
  momentum: 0.0
  warmup_steps: 0
  warmup_ratio: 0.0
  scheduler: "cosine"
  gradient_clip_val: 1.0

data:
  train_datasets:
    - pmemo2019
  val_datasets:
    - pmemo2019
  test_datasets:
    - pmemo2019
  batch_size: 64
  num_workers: 8
  prefetch_size: 4

loss:
  name: "huber"

hardware:
  device: "cuda"
  precision: "fp16"
  distributed: True
  num_gpus: 2

logging:
  wandb_project: "audio2eda"
  wandb_entity: null
  wandb_run_name: "Example2_Run"
  wandb_tags: []
  log_every_n_steps: 25
  log_config: true
  compute_metrics: true
  train_metrics:
    - "loss"
  val_metrics:
    - "loss"
    - "mse"
    - "dtw"
  val_check_interval: 1.0
  early_stopping: true
  early_stopping_patience: 10
  early_stopping_min_delta: 0.0001

checkpoint:
  save_top_k: 5
  checkpoint_dir: "checkpoints/example2"
  monitor: "val_dtw"
  mode: "min"
  save_last: True
  save_every_n_steps: 500
  load_from_checkpoint: null

train:
  max_epochs: 100
  accumulate_grad_batches: 1
