experiment_name: "Example1"
seed: 42

model:
  architecture: "tcn"
  params:
    input_size: 40  # Number of input features (e.g., MFCC features)
    output_size: 1  # EDA signal output
    num_blocks: 5
    num_channels: 64
    kernel_size: 3
    dropout: 0.2

optimizer:
  name: "adamw"
  learning_rate: 0.0001
  weight_decay: 0.01
  beta1: 0.9
  beta2: 0.999
  momentum: 0.0
  warmup_steps: 0
  warmup_ratio: 0.0
  scheduler: "constant"
  gradient_clip_val: 1.0

data:
  train_datasets:
    - hku956
  val_datasets:
    - hku956
  test_datasets:
    - hku956
  batch_size: 32
  num_workers: 4
  prefetch_size: 2

loss:
  name: "mse"

hardware:
  device: "mps"
  precision: "fp32"  # MPS only supports fp32
  distributed: False # MPS doesn't support distributed training
  num_gpus: 1        # MPS only supports a single GPU

logging:
  wandb_project: "audio2eda"
  wandb_entity: null
  wandb_run_name: "Example1_Run"
  wandb_tags: []
  log_every_n_steps: 50
  log_config: true
  compute_metrics: true
  train_metrics:
    - "loss"
  val_metrics:
    - "loss"
    - "mse"
  val_check_interval: 1.0
  early_stopping: true
  early_stopping_patience: 10
  early_stopping_min_delta: 0.0001

checkpoint:
  save_top_k: 3
  checkpoint_dir: "checkpoints/example1"
  monitor: "val_loss"
  mode: "min"
  save_last: True
  save_every_n_steps: 1000
  load_from_checkpoint: null

train:
  max_epochs: 100
  accumulate_grad_batches: 1
