experiment_name: "ResidualUpsampler_Invalid"
seed: 42

model:
  architecture: "residual_upsampler"
  params:
    upsampling_factor: 2
    in_channels: 40
    out_channels: 1  # Missing required field 'hidden_channels' makes this configuration invalid.

optimizer:
  name: "adam"
  learning_rate: 0.0002
  weight_decay: 0.001
  beta1: 0.9
  beta2: 0.999
  momentum: 0.0
  warmup_steps: 0
  warmup_ratio: 0.0
  scheduler: "constant"
  gradient_clip_val: 1.0

data:
  train_datasets:
    - hku956
  val_datasets:
    - hku956
  test_datasets:
    - hku956
  batch_size: 32
  num_workers: 4
  prefetch_size: 2

loss:
  name: "mse"

hardware:
  device: "cuda"
  precision: "fp16"
  distributed: false
  num_gpus: 1

metrics:
  compute_metrics: true
  train_metrics:
    - "loss"
  val_metrics:
    - "loss"
    - "mse"
  val_check_interval: 1.0
  early_stopping: true
  early_stopping_patience: 10
  early_stopping_min_delta: 0.0001

logging:
  wandb_project: "audio2eda"
  wandb_entity: null
  wandb_run_name: "ResidualUpsampler_Invalid_Run"
  wandb_tags:
    - "invalid"
    - "residual_upsampler"
    - "test"
  log_every_n_steps: 50

checkpoint:
  save_top_k: 3
  checkpoint_dir: "checkpoints/residual_upsampler_invalid"
  monitor: "val_loss"
  mode: "min"
  save_last: true
  save_every_n_steps: 1000
  load_from_checkpoint: null

train:
  max_epochs: 100
  accumulate_grad_batches: 1
